### PR TITLE
Bug for the annotation related to the operation

### PR DESCRIPTION
**Pull request by alexromero88**
I have found a bug when the item is provided for the annotation ApiOperation. The change is small, so I really appreciate if you can include it and generate a new release.

Thanks

### CODE REVIEW

**Comment by rahulsom** [comment]
Can you please add a unit test?

**Comment by alexromero88** [comment]
Unit test added

**Comment by alexromero88** [comment]
Thanks! When do you think you will be able to release the new version?

**Comment by rahulsom** [comment]
I've just pushed out a release.

**Pull request merged**
