### PR TITLE
Support for dynamic discovery of settings

### PR DESCRIPTION
**Pull request by gefilte**
These changes are aimed at having less dependence on annotations for auto-generation of documentation. It supports using UrlMappings to create resource mapping to controllers, including hierarchical relationships (e.g. /outer/{outerId}/inner/{id}.) It also has optional support for the marshallers plugin for controlling how domains are emitted.

Let me know what you think!

### CODE REVIEW

**Comment by rahulsom** [comment]
@gefilte The changes look great. However it looks like one of the tests is failing - https://travis-ci.org/rahulsom/swaggydoc/builds/51590913

**Comment by gefilte** [comment]
Thanks. My bad on the failing tests. One of those last-second changes before pushing... I added some sense to it.

**Comment by rahulsom** [comment]
[LGTM](http://www.lgtm.in/i/OjnORIo9q)

[:+1:](http://www.lgtm.in/u/OjnORIo9q) [:-1:](http://www.lgtm.in/r/OjnORIo9q)

**Comment by rahulsom** [comment]
Thanks for your work. It makes a lot of things very clean.

**Comment by gefilte** [comment]
Thanks! Got another minor change coming your way...

**Pull request merged**
